services:
  mailflow:
    build: .
    container_name: mailflow
    restart: always
    volumes:
      - ${MAILFLOW_CONFIG_DIR:-./config}:/config
    environment:
      - TZ=${TZ:-America/Los_Angeles}
    ports:
      - "8792:8792"
